#define thisIsForWhenTheButtonIsNotBeingHoveredOverByTheMouseOrBeingClicked normal
#define thisIsUnlikeTheAboveImageAndIsForWhenTheUserClicksOntoTheButtonWithTheMouse clicked
#define andFinallyThisIsForWhenTheUserIsNotClickingTheMouseButIsJustHoveringOverItWithTheMouse hover
#define stupidGraphicsType pixmap
#define fuckingPointers *